### ISSUE TITLE
Missing the similar topics in the frontend

### ISSUE THREAD

**Issue by AlexL777** [VSEphpbb/similartopics#18]
Hello Developer,

Unfortunately I have a problem with this extension **with PHPBB 3.2 RC 2**. The Similar Topics in the frontend under the Forum Post are missed. 

Have a look at http://wpzweinull.ch/cms/phpbb32/phpbb-3-2-forum-f2/phpbb-3-2-update-auf-rc-2-erfolgreich-t13.html#p19 it.

Can you help me somehow or does this extension with the new PHPBB version very well?

Thanks in advance.

**Comment by VSEphpbb** [comment]
The current version is not compatible with phpBB 3.2. You have to wait for the next version in a few weeks/months.
